setStructure = set()
print(setStructure)
print(hex(id(setStructure)))
setStructure.add(3)
print(setStructure)
print(hex(id(setStructure)))
setStructure.add(4)
print(setStructure)
print(hex(id(setStructure)))
setStructure.add(4)
print(setStructure)
print(hex(id(setStructure)))
setStructure.discard(4)
print(setStructure)
print(hex(id(setStructure)))
setStructure.discard(4)
print(setStructure)
print(hex(id(setStructure)))
setList = set([1,2,3])
setList.update([4])
print(setList)
print(hex(id(setList)))
print(setList.pop())
print(setList.pop())
print(setList.pop())
setList.difference_update([4,5])
print(setList)
